### ISSUE TITLE
Poet links color 

### ISSUE THREAD

**Issue by easbarba** [kunalb/poet#12]
Hi,

Poet link colors is not gracefully matching its color scheme. I might be wrong  but it seems Poet is using Emacs default link color.

https://i.ibb.co/2MSGV11/shot-2019-02-07-T08-35-14-02-00.png

 Thanks!

**Comment by kunalb** [comment]
Hmm, I'll take another look in a few weeks (a bit busy with other stuff atm). I vaguely remember choosing blue explicitly because it's the "recognized" link color. I've also never opened an .epub file in emacs or poet, I'm sure there are other things that need to be fixed for those.

(I'm not sure why you closed this issue though?)

**Comment by easbarba** [comment]
Oh, great, thanks! 

(lol)

**Comment by kunalb** [comment]
(Sanity checked epubs)
